### ISSUE TITLE
Failed to migrate knex database

### ISSUE THREAD

**Issue by brunolnetto** [robmclarty/knex-express-project-sample#14]
I followed the steps below:

OS: Linux 20.04

1. Clone the  repository;
2. Run command `npm install` on root folder;
3. Run command `npm run db:migrate` on root folder; 

I received the log below after message `Using environment: development`. I require some instructions to reproduce this repository behaviour and features.

```
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /home/brunolnetto/github/knex-express-project-sample/node_modules/knex/lib/client.js:348:17
    at tryCatcher (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/util.js:16:23)
    at /home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/brunolnetto/github/knex-express-project-sample/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
```

**Comment by robmclarty** [comment]
Hmm, if those are the only steps you took, it might be because the database is missing/offline? By default, the `knexfile.js` will be looking at `postgres://localhost:5432/knex-test` for a local postgres database named `knex-test` running on port `5432`. Maybe check that out and adjust the configuration to your environment and try it again ;)

Also of interest: I just recently published a new package I'm working on called `storium` which attempts to encapsulate much of what this template repo is trying to do. I'll be making another template/starter app eventually, but worth checking out if you like this way of organizing things: https://github.com/robmclarty/storium

**Comment by brunolnetto** [comment]
Cool cool! I found out I need to up the database first 😅. A great idea would be to generate a package for a multiple-entry database with cartesian-product between `(mySQL, Postgres, MariaDB, database-1, database-n)` with environments `(development, homolog, production, docker)`. 

I will take a look at `storium` and provide further feedback on my progress. :-)

**Comment by robmclarty** [comment]
ok, cheers :)
